package:
  name: caffe2
  version: "{{ environ.get('CAFFE2_BUILD_VERSION') }}"

source:
  git_url: https://github.com/pytorch/pytorch.git
  git_rev: "{{ environ.get('PYTORCH_GIT_HASH') }}"

build:
  number: {{ environ.get('CAFFE2_BUILD_NUMBER') }}
  skip: True  # [win]

requirements:
  build:
    - protobuf==3.5.2
  run:
    - protobuf==3.5.2

about:
  home: https://caffe2.ai/
  license: BSD
  summary: Caffe2 is a lightweight, modular, and scalable deep learning framework.
